[behave]
# Configuración de salida por defecto
stdout_capture = False
stderr_capture = False
log_capture = False

# Definir idioma en español por si querés escribir "Dado/Cuando/Entonces"
# default_language = es

[behave.userdata]
# Variables de entorno personalizables desde consola si hiciese falta
browser = chrome