[pytest]
# Dejamos solo las banderas estándar de reportes y reintentos
addopts = -v --strict-markers --html=reports/report.html --self-contained-html --reruns 1

markers =
    smoke: Pruebas críticas de humo para el flujo del carrito (UI)
    web: Pruebas de interfaz de usuario con Selenium
    api: Pruebas de validación de endpoints y servicios HTTP
    e2e: Flujos completos de fin a fin e integraciones CRUD (API/UI)
	bdd: Pruebas de comportamiento basadas en Behave (.feature)